---
title: "Data stucture"
date: "2019-05-27"
categories: Coding
tags: [python, R]
---

# Array

Some languages (including Python) don't have these bare-bones arrays.

Don't want to specify the size of your array ahead of time? One option: use a dynamic array.

Want to look up items by something other than an index? Use a dictionary.

## Strengths:

1. *Fast lookups.* Retrieving the element at a given index takes O(1) time, regardless of the length of the array.
2. *Fast appends.* Adding a new element at the end of the array takes O(1) time.

## Weaknesses:

1. *Fixed size.* You need to specify how many elements you're going to store in your array ahead of time. (Unless you're using a fancy dynamic array.)
2. *Costly inserts* and deletes. You have to "scoot over" the other elements to fill in or close gaps, which takes worst-case O(n)O(n) time.


## Array Slicing

Array slicing involves taking a subset from an array and **allocating a new array** with those elements.

This takes O(n) time and O(n) space, where nn is the number of elements in the resulting list.

```{python}

tail_of_list = my_list[1:]

return my_list[1:]
# Whoops, I just spent O(n) time and space!

for item in my_list[1:]:
    # Whoops, I just spent O(n) time and space!
    pass

```


## in-place algorithm:

An **in-place** algorithm operates directly on its input and changes it, instead of creating and returning a new object. This is sometimes called destructive, since the original input is "destroyed" when it's edited to create the new output.

Generally, out-of-place algorithms are considered safer because they avoid side effects. You should only use an in-place algorithm if you're very space constrained or you're positive you don't need the original input anymore, even for debugging.

Becareful of the difference in python and R! R dont do in-replace.

**Python**

```{python}
#in-replace
def square_list_in_place(int_list):
    for index in range(len(int_list)):
        int_list[index] = int_list[index] *3

    # NOTE: We could make this function just return, since
    # we modify int_list in place.
    return int_list

original_list = [2, 3, 4, 5]
squared_list  = square_list_in_place(original_list)
squared_list
original_list

#out-replace
def square_list_out_of_place(int_list):
    # We allocate a new list with the length of the input list
    squared_list = [None] * len(int_list)

    for index, element in enumerate(int_list):
        squared_list[index] = element ** 2

    return squared_list

```

**R**

```{R}

squared_list = NULL
alt <- function (original) {
  for (i in 1:length(original)) {
    original[i]=original[i]*2
  }
  return(original)
}

original_list=c(1,2,3,4)
squared_list <- alt(original_list)
squared_list
original_list
```

# Dynamic Array

automatic resizing. 

In Python, dynamic arrays are called lists.

## Strengths:

1. **Fast lookups.** Just like arrays, retrieving the element at a given index takes O(1)  time.
2. **Variable size.** You can add as many items as you want, and the dynamic array will expand to hold them.
3. **Cache-friendly.** Just like arrays, dynamic arrays place items right next to each other in memory, making efficient use of caches.

## Weaknesses:

1. **Slow worst-case appends.** Usually, adding a new element at the end of the dynamic array takes O(1) time. But if the dynamic array doesn't have any room for the new item, it'll need to expand, which takes O(n)time. 
2. **Costly inserts and deletes.** Just like arrays, elements are stored adjacent to each other. So adding or removing an item in the middle of the array requires "scooting over" other elements, which takes O(n)  time.


## Doubling Appends

To make room, dynamic arrays automatically make a new, bigger underlying array. Usually twice as big.

In industry we usually wave our hands and say dynamic arrays have a time cost of O(1)  for appends, even though strictly speaking that's only true for the average case or the amortized cost. The cost of doing mm appends has two parts:

  a. The cost of actually appending all mm items.
  
  b. The cost of any "doubling" we need to do along the way.